name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        cache: 'npm'
    - name: Install packages
      run: yarn
    - name: Create build
      run: yarn build
    - name: Jekyll build
      uses: actions/jekyll-build-pages@main
      with:
        source: ./build/
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}