name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        cache: 'npm'
    - name: Install packages
      run: yarn
    - name: Create build
      run: yarn build
    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@main
      with:
        path: build/
    - name: Deploy Github Pages
      uses: actions/deploy-pages@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}