name: Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        cache: 'npm'
    - name: Install packages
      run: yarn
    - name: Create build
      run: yarn build
    - name: Archive build
      run: tar --dereference --hard-dereference --directory "build/" -cvf ${{ runner.temp }}/artifact.tar .
    - name: Upload build to Github Pages
      uses: actions/upload-artifact@main
      with:
        name: github-pages
        path: ${{ runner.temp }}/artifact.tar
        retention-days: 1
    - name: Deploy Github Pages
      uses: actions/deploy-pages@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}